# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../asset/tpl/ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/asset/img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.showTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.showTextEdit.setReadOnly(True)
        self.showTextEdit.setObjectName("showTextEdit")
        self.gridLayout.addWidget(self.showTextEdit, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(701, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.remainLabel = QtWidgets.QLabel(self.centralwidget)
        self.remainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remainLabel.setObjectName("remainLabel")
        self.gridLayout.addWidget(self.remainLabel, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        self.menu_S = QtWidgets.QMenu(self.menubar)
        self.menu_S.setObjectName("menu_S")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.open = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/asset/img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open.setIcon(icon1)
        self.open.setObjectName("open")
        self.save = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/asset/img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon2)
        self.save.setObjectName("save")
        self.addClass = QtWidgets.QAction(MainWindow)
        self.addClass.setObjectName("addClass")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.testAction = QtWidgets.QAction(MainWindow)
        self.testAction.setObjectName("testAction")
        self.close = QtWidgets.QAction(MainWindow)
        self.close.setObjectName("close")
        self.quit = QtWidgets.QAction(MainWindow)
        self.quit.setObjectName("quit")
        self.menu_F.addAction(self.open)
        self.menu_F.addAction(self.save)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.close)
        self.menu_F.addAction(self.quit)
        self.menu_E.addAction(self.testAction)
        self.menu_S.addAction(self.about)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_S.menuAction())
        self.toolBar.addAction(self.addClass)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手动文本分类"))
        self.label.setText(_translate("MainWindow", "剩余条数："))
        self.remainLabel.setText(_translate("MainWindow", "0"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menu_S.setTitle(_translate("MainWindow", "设置(&S)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.open.setText(_translate("MainWindow", "打开"))
        self.open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.addClass.setText(_translate("MainWindow", "添加分类"))
        self.addClass.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.about.setText(_translate("MainWindow", "关于"))
        self.testAction.setText(_translate("MainWindow", "测试"))
        self.close.setText(_translate("MainWindow", "关闭"))
        self.close.setIconText(_translate("MainWindow", "关闭"))
        self.quit.setText(_translate("MainWindow", "退出"))
import img_rc
